name: VollVertnuettelt
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - ipython
  - jupyter
  - jupyterlab
  - pandas
  - numpy
  - matplotlib
  - seaborn
  - scipy
  - scikit-learn
  - graphviz
  - python-graphviz
  - py-xgboost
  - wordcloud
  - pip:
    - sidetable
    - torch
    - keras
    - nltk
    - pmdarima
    - tensorflow
    - twscrape
    - python-dotenv
    - langdetect
    - tqdm
    - transformers
    - plotly
    - nrclex
    - nltk